Revert "click_events: use epoll"
This reverts commit 13432afca8b0b35ed5197761c05fa8c4f67ecd1f.

Reverted for the time being, there seems to be an issue in removing
fds:

thread '<unnamed>' panicked at 'epoll::ctl failed when removing fd: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', src/clicky_events.rs:176:18